LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

ifeq ($(shell test $(TWRP_DEVICE_VERSION) -ge 0; echo $$?),0)
    TW_DEVICE_VERSION := $(TW_DEVICE_VERSION)
    LOCAL_CFLAGS += -DTW_DEVICE_VERSION=$(TW_DEVICE_VERSION)
else
    TW_DEVICE_VERSION := 0 
    LOCAL_CFLAGS += -DTW_DEVICE_VERSION=$(TW_DEVICE_VERSION)
endif

LOCAL_SRC_FILES:= \
	orscmd.cpp
LOCAL_CFLAGS += -c -W
LOCAL_MODULE := orscmd
LOCAL_MODULE_STEM := twrp
LOCAL_MODULE_TAGS:= eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
include $(BUILD_EXECUTABLE)
