.\" Copyright (C) 2010-2015  Andrew Nayenko
.\"
.TH EXFAT-FUSE 8 "July 2010"
.SH NAME
mount.exfat-fuse \- mount an exFAT file system
.SH SYNOPSIS
.B mount.exfat-fuse
[
.B \-d
]
[
.B \-n
]
[
.B \-o
.I options
]
[
.B \-V
]
[
.B \-v
]
.I device dir

.SH DESCRIPTION
.B mount.exfat-fuse
is a free exFAT file system implementation with write support. exFAT is a
simple file system created by Microsoft. It is intended to replace FAT32
removing some of its limitations. exFAT is a standard FS for SDXC memory
cards.

.SH COMMAND LINE OPTIONS
Command line options available:
.TP
.BI \-d
Enable debug logging and do not detach from shell.
.TP
.BI \-n
Ignored.
.TP
.BI \-o " options"
File system specific options. For more details see
.B FILE SYSTEM OPTIONS
section below.
.TP
.BI \-V
Print version and copyright.
.TP
.BI \-v
Ignored.

.SH FILE SYSTEM OPTIONS
.TP
.BI umask= value
Set the umask (the bitmask of the permissions that are
.B not
present, in octal).
The default is 0.
.TP
.BI dmask= value
Set the umask for directories only.
.TP
.BI fmask= value
Set the umask for files only.
.TP
.BI uid= n
Set the owner for all files and directories.
The default is the owner of the current process.
.TP
.BI gid= n
Set the group for all files and directories.
The default is the group of the current process.
.TP
.BI ro
Mount the file system in read only mode.
.TP
.BI noatime
Do not update access time when file is read.

.SH EXIT CODES
Zero is returned on successful mount. Any other code means an error.

.SH BUGS
exFAT is a case-insensitive file system. Some things can behave unexpectedly,
e.g. directory renaming that changes only case of some characters:

.B \t$ mv FOO Foo
.br
.B \tmv: cannot move \(cqFOO\(cq to a subdirectory of itself, \(cqFoo/FOO\(cq

This happens because
.B mv
finds that destination exists (for case-insensitive file
systems
.B FOO
and
.B Foo
are the same thing) and adds source basename to the destination. The file
system gets
.B rename(\(dqFOO\(dq,\ \(dqFoo/FOO\(dq)
syscall and returns an error.

.SH AUTHOR
Andrew Nayenko

.SH SEE ALSO
.BR mount (8)
